server:
  port=: 8080
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      name: defaultDataSource
      url: jdbc:mysql://localhost:3306/j2eefinalexam?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: zj1017
# 配置数据库日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
